{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "ac48f4ae",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-04-15 15:27:44,709\tINFO worker.py:1553 -- Started a local Ray instance.\n"
     ]
    }
   ],
   "source": [
    "# Load Data\n",
    "import pandas as pd\n",
    "import ray\n",
    "\n",
    "ray.shutdown()\n",
    "ray.init(object_store_memory=4000000000) # set object store memory to 4GB\n",
    "\n",
    "data = pd.read_pickle('C:\\\\Users\\\\manue\\\\switchdrive\\\\Mutual Funds Project\\\\data\\\\pickle_files\\\\full_dataset.pkl')\n",
    "sample = data.sample(101, random_state=1)\n",
    "\n",
    "# tansform 'Rating' from Categorical to float\n",
    "import numpy as np\n",
    "sample[\"Rating\"] = pd.to_numeric(sample[\"Rating\"], errors='coerce')\n",
    "\n",
    "# drop all rows with inf/-inf values!\n",
    "import numpy as np\n",
    "sample = sample[(sample != np.inf).all(axis=1)]\n",
    "sample = sample[(sample != -np.inf).all(axis=1)]\n",
    "\n",
    "#get rid of whitespace to draw tree later\n",
    "Eq_Stylebox = sample['Eq_Stylebox_Long'].astype('object').replace(' ','_', regex=True)\n",
    "sample['Eq_Stylebox_Long'] = Eq_Stylebox.astype('category')\n",
    "\n",
    "# shifting target variable to predict next month\n",
    "sample['returns'] = sample.returns.shift(-1)\n",
    "sample = sample.drop(sample.tail(1).index)\n",
    "\n",
    "\n",
    "X = sample.drop('returns', axis=1)\n",
    "y = sample['returns']\n",
    "\n",
    "# create dummies in case of categorical data\n",
    "dummy_needed = [#'Rating',\n",
    "                'Financial_Health_Grade_Long',\n",
    "                 'Growth_Grade_Long',\n",
    "                 'Profitability_Grade_Long',\n",
    "                 'Eq_Stylebox_Long']\n",
    "\n",
    "X = pd.get_dummies(X, columns=dummy_needed)\n",
    "\n",
    "# Split\n",
    "from sklearn.model_selection import train_test_split\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 26)\n",
    "#X_train = ray.put(X_train)\n",
    "#y_train = ray.put(y_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "0f59d933",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div class=\"tuneStatus\">\n",
       "  <div style=\"display: flex;flex-direction: row\">\n",
       "    <div style=\"display: flex;flex-direction: column;\">\n",
       "      <h3>Tune Status</h3>\n",
       "      <table>\n",
       "<tbody>\n",
       "<tr><td>Current time:</td><td>2023-04-15 15:29:34</td></tr>\n",
       "<tr><td>Running for: </td><td>00:01:17.50        </td></tr>\n",
       "<tr><td>Memory:      </td><td>8.6/15.7 GiB       </td></tr>\n",
       "</tbody>\n",
       "</table>\n",
       "    </div>\n",
       "    <div class=\"vDivider\"></div>\n",
       "    <div class=\"systemInfo\">\n",
       "      <h3>System Info</h3>\n",
       "      Using AsyncHyperBand: num_stopped=0<br>Bracket: Iter 64.000: None | Iter 16.000: None | Iter 4.000: None | Iter 1.000: None<br>Resources requested: 0/8 CPUs, 0/0 GPUs, 0.0/0.37 GiB heap, 0.0/3.73 GiB objects\n",
       "    </div>\n",
       "    <div class=\"vDivider\"></div>\n",
       "<div class=\"messages\">\n",
       "  <h3>Messages</h3>\n",
       "  \n",
       "  \n",
       "  Number of errored trials: 10<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name        </th><th style=\"text-align: right;\">  # failures</th><th>error file                                                                                                                                                                                                                                               </th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>objective_bb5b8fc1</td><td style=\"text-align: right;\">           1</td><td>C:\\Users\\manue\\switchdrive\\Mutual Funds Project\\ml_prediction\\ray_results\\xgboost_tuning\\objective_bb5b8fc1_1_colsample_bylevel=0.8949,colsample_bytree=0.7125,learning_rate=0.0026,max_depth=5,n_estimators=3642,reg_alpha_2023-04-15_15-28-21\\error.txt</td></tr>\n",
       "<tr><td>objective_9a68262f</td><td style=\"text-align: right;\">           1</td><td>C:\\Users\\manue\\switchdrive\\Mutual Funds Project\\ml_prediction\\ray_results\\xgboost_tuning\\objective_9a68262f_2_colsample_bylevel=0.9858,colsample_bytree=0.8355,learning_rate=0.0002,max_depth=15,n_estimators=7269,reg_alph_2023-04-15_15-28-31\\error.txt</td></tr>\n",
       "<tr><td>objective_1548b759</td><td style=\"text-align: right;\">           1</td><td>C:\\Users\\manue\\switchdrive\\Mutual Funds Project\\ml_prediction\\ray_results\\xgboost_tuning\\objective_1548b759_3_colsample_bylevel=0.8083,colsample_bytree=0.7469,learning_rate=0.0005,max_depth=7,n_estimators=7170,reg_alpha_2023-04-15_15-28-34\\error.txt</td></tr>\n",
       "<tr><td>objective_a966dd12</td><td style=\"text-align: right;\">           1</td><td>C:\\Users\\manue\\switchdrive\\Mutual Funds Project\\ml_prediction\\ray_results\\xgboost_tuning\\objective_a966dd12_4_colsample_bylevel=0.9312,colsample_bytree=0.5091,learning_rate=0.4007,max_depth=1,n_estimators=8327,reg_alpha_2023-04-15_15-28-37\\error.txt</td></tr>\n",
       "<tr><td>objective_957dbe26</td><td style=\"text-align: right;\">           1</td><td>C:\\Users\\manue\\switchdrive\\Mutual Funds Project\\ml_prediction\\ray_results\\xgboost_tuning\\objective_957dbe26_5_colsample_bylevel=0.8806,colsample_bytree=0.9334,learning_rate=0.0032,max_depth=8,n_estimators=6172,reg_alpha_2023-04-15_15-28-49\\error.txt</td></tr>\n",
       "<tr><td>objective_ce4aab15</td><td style=\"text-align: right;\">           1</td><td>C:\\Users\\manue\\switchdrive\\Mutual Funds Project\\ml_prediction\\ray_results\\xgboost_tuning\\objective_ce4aab15_6_colsample_bylevel=0.5527,colsample_bytree=0.7654,learning_rate=0.1789,max_depth=11,n_estimators=8759,reg_alph_2023-04-15_15-28-52\\error.txt</td></tr>\n",
       "<tr><td>objective_db4170ce</td><td style=\"text-align: right;\">           1</td><td>C:\\Users\\manue\\switchdrive\\Mutual Funds Project\\ml_prediction\\ray_results\\xgboost_tuning\\objective_db4170ce_7_colsample_bylevel=0.9237,colsample_bytree=0.6934,learning_rate=0.1925,max_depth=12,n_estimators=7402,reg_alph_2023-04-15_15-29-01\\error.txt</td></tr>\n",
       "<tr><td>objective_a9008590</td><td style=\"text-align: right;\">           1</td><td>C:\\Users\\manue\\switchdrive\\Mutual Funds Project\\ml_prediction\\ray_results\\xgboost_tuning\\objective_a9008590_8_colsample_bylevel=0.7176,colsample_bytree=0.7672,learning_rate=0.2112,max_depth=13,n_estimators=5199,reg_alph_2023-04-15_15-29-11\\error.txt</td></tr>\n",
       "<tr><td>objective_2c5bede9</td><td style=\"text-align: right;\">           1</td><td>C:\\Users\\manue\\switchdrive\\Mutual Funds Project\\ml_prediction\\ray_results\\xgboost_tuning\\objective_2c5bede9_9_colsample_bylevel=0.7408,colsample_bytree=0.9965,learning_rate=0.0039,max_depth=5,n_estimators=4795,reg_alpha_2023-04-15_15-29-15\\error.txt</td></tr>\n",
       "<tr><td>objective_e5d33a9b</td><td style=\"text-align: right;\">           1</td><td>C:\\Users\\manue\\switchdrive\\Mutual Funds Project\\ml_prediction\\ray_results\\xgboost_tuning\\objective_e5d33a9b_10_colsample_bylevel=0.6709,colsample_bytree=0.9663,learning_rate=0.5783,max_depth=2,n_estimators=2969,reg_alph_2023-04-15_15-29-26\\error.txt</td></tr>\n",
       "</tbody>\n",
       "</table>\n",
       "</div>\n",
       "<style>\n",
       ".messages {\n",
       "  color: var(--jp-ui-font-color1);\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "  padding-left: 1em;\n",
       "  overflow-y: auto;\n",
       "}\n",
       ".messages h3 {\n",
       "  font-weight: bold;\n",
       "}\n",
       ".vDivider {\n",
       "  border-left-width: var(--jp-border-width);\n",
       "  border-left-color: var(--jp-border-color0);\n",
       "  border-left-style: solid;\n",
       "  margin: 0.5em 1em 0.5em 1em;\n",
       "}\n",
       "</style>\n",
       "\n",
       "  </div>\n",
       "  <div class=\"hDivider\"></div>\n",
       "  <div class=\"trialStatus\">\n",
       "    <h3>Trial Status</h3>\n",
       "    <table>\n",
       "<thead>\n",
       "<tr><th>Trial name        </th><th>status  </th><th>loc            </th><th style=\"text-align: right;\">  colsample_bylevel</th><th style=\"text-align: right;\">  colsample_bytree</th><th style=\"text-align: right;\">  learning_rate</th><th style=\"text-align: right;\">  max_depth</th><th style=\"text-align: right;\">  n_estimators</th><th style=\"text-align: right;\">  reg_alpha</th><th style=\"text-align: right;\">  reg_lambda</th><th style=\"text-align: right;\">  subsample</th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>objective_bb5b8fc1</td><td>ERROR   </td><td>127.0.0.1:20372</td><td style=\"text-align: right;\">           0.8949  </td><td style=\"text-align: right;\">          0.712453</td><td style=\"text-align: right;\">    0.00257991 </td><td style=\"text-align: right;\">          5</td><td style=\"text-align: right;\">          3642</td><td style=\"text-align: right;\"> 0.0329368 </td><td style=\"text-align: right;\">  1.16658   </td><td style=\"text-align: right;\">   0.666029</td></tr>\n",
       "<tr><td>objective_9a68262f</td><td>ERROR   </td><td>127.0.0.1:8604 </td><td style=\"text-align: right;\">           0.985777</td><td style=\"text-align: right;\">          0.835472</td><td style=\"text-align: right;\">    0.000173412</td><td style=\"text-align: right;\">         15</td><td style=\"text-align: right;\">          7269</td><td style=\"text-align: right;\"> 0.0122288 </td><td style=\"text-align: right;\">  0.167461  </td><td style=\"text-align: right;\">   0.642125</td></tr>\n",
       "<tr><td>objective_1548b759</td><td>ERROR   </td><td>127.0.0.1:18840</td><td style=\"text-align: right;\">           0.808272</td><td style=\"text-align: right;\">          0.746942</td><td style=\"text-align: right;\">    0.000454984</td><td style=\"text-align: right;\">          7</td><td style=\"text-align: right;\">          7170</td><td style=\"text-align: right;\"> 0.406775  </td><td style=\"text-align: right;\">  8.47337   </td><td style=\"text-align: right;\">   0.645359</td></tr>\n",
       "<tr><td>objective_a966dd12</td><td>ERROR   </td><td>127.0.0.1:25588</td><td style=\"text-align: right;\">           0.931209</td><td style=\"text-align: right;\">          0.509122</td><td style=\"text-align: right;\">    0.400696   </td><td style=\"text-align: right;\">          1</td><td style=\"text-align: right;\">          8327</td><td style=\"text-align: right;\"> 0.00188912</td><td style=\"text-align: right;\">  2.73568   </td><td style=\"text-align: right;\">   0.523635</td></tr>\n",
       "<tr><td>objective_957dbe26</td><td>ERROR   </td><td>127.0.0.1:27200</td><td style=\"text-align: right;\">           0.880617</td><td style=\"text-align: right;\">          0.93338 </td><td style=\"text-align: right;\">    0.00324613 </td><td style=\"text-align: right;\">          8</td><td style=\"text-align: right;\">          6172</td><td style=\"text-align: right;\"> 0.00354872</td><td style=\"text-align: right;\">  0.00203326</td><td style=\"text-align: right;\">   0.730872</td></tr>\n",
       "<tr><td>objective_ce4aab15</td><td>ERROR   </td><td>127.0.0.1:12576</td><td style=\"text-align: right;\">           0.552719</td><td style=\"text-align: right;\">          0.765447</td><td style=\"text-align: right;\">    0.178906   </td><td style=\"text-align: right;\">         11</td><td style=\"text-align: right;\">          8759</td><td style=\"text-align: right;\"> 0.0154599 </td><td style=\"text-align: right;\">  0.10678   </td><td style=\"text-align: right;\">   0.932481</td></tr>\n",
       "<tr><td>objective_db4170ce</td><td>ERROR   </td><td>127.0.0.1:9952 </td><td style=\"text-align: right;\">           0.923694</td><td style=\"text-align: right;\">          0.693447</td><td style=\"text-align: right;\">    0.192454   </td><td style=\"text-align: right;\">         12</td><td style=\"text-align: right;\">          7402</td><td style=\"text-align: right;\"> 0.566774  </td><td style=\"text-align: right;\">  0.610257  </td><td style=\"text-align: right;\">   0.509154</td></tr>\n",
       "<tr><td>objective_a9008590</td><td>ERROR   </td><td>127.0.0.1:26844</td><td style=\"text-align: right;\">           0.71758 </td><td style=\"text-align: right;\">          0.767246</td><td style=\"text-align: right;\">    0.21125    </td><td style=\"text-align: right;\">         13</td><td style=\"text-align: right;\">          5199</td><td style=\"text-align: right;\"> 0.00615445</td><td style=\"text-align: right;\">  0.473912  </td><td style=\"text-align: right;\">   0.558816</td></tr>\n",
       "<tr><td>objective_2c5bede9</td><td>ERROR   </td><td>127.0.0.1:16108</td><td style=\"text-align: right;\">           0.740751</td><td style=\"text-align: right;\">          0.996489</td><td style=\"text-align: right;\">    0.00387391 </td><td style=\"text-align: right;\">          5</td><td style=\"text-align: right;\">          4795</td><td style=\"text-align: right;\">29.0498    </td><td style=\"text-align: right;\">  1.10826   </td><td style=\"text-align: right;\">   0.536911</td></tr>\n",
       "<tr><td>objective_e5d33a9b</td><td>ERROR   </td><td>127.0.0.1:5388 </td><td style=\"text-align: right;\">           0.670944</td><td style=\"text-align: right;\">          0.966261</td><td style=\"text-align: right;\">    0.578286   </td><td style=\"text-align: right;\">          2</td><td style=\"text-align: right;\">          2969</td><td style=\"text-align: right;\"> 1.04228   </td><td style=\"text-align: right;\">  0.00107675</td><td style=\"text-align: right;\">   0.888869</td></tr>\n",
       "</tbody>\n",
       "</table>\n",
       "  </div>\n",
       "</div>\n",
       "<style>\n",
       ".tuneStatus {\n",
       "  color: var(--jp-ui-font-color1);\n",
       "}\n",
       ".tuneStatus .systemInfo {\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "}\n",
       ".tuneStatus td {\n",
       "  white-space: nowrap;\n",
       "}\n",
       ".tuneStatus .trialStatus {\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "}\n",
       ".tuneStatus h3 {\n",
       "  font-weight: bold;\n",
       "}\n",
       ".tuneStatus .hDivider {\n",
       "  border-bottom-width: var(--jp-border-width);\n",
       "  border-bottom-color: var(--jp-border-color0);\n",
       "  border-bottom-style: solid;\n",
       "}\n",
       ".tuneStatus .vDivider {\n",
       "  border-left-width: var(--jp-border-width);\n",
       "  border-left-color: var(--jp-border-color0);\n",
       "  border-left-style: solid;\n",
       "  margin: 0.5em 1em 0.5em 1em;\n",
       "}\n",
       "</style>\n"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-04-15 15:28:31,730\tERROR trial_runner.py:1062 -- Trial objective_bb5b8fc1: Error processing event.\n",
      "ray.exceptions.RayTaskError(ValueError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=20372, ip=127.0.0.1, repr=objective)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 803, in ray._raylet.execute_task.function_executor\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 674, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\trainable.py\", line 368, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 337, in entrypoint\n",
      "    return self._trainable_func(\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 654, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<timed exec>\", line 28, in objective\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 105, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\worker.py\", line 2369, in get\n",
      "    raise ValueError(\n",
      "ValueError: 'object_refs' must either be an ObjectRef or a list of ObjectRefs.\n",
      "2023-04-15 15:28:44,983\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=8604, ip=127.0.0.1, repr=objective)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 803, in ray._raylet.execute_task.function_executor\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 674, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\trainable.py\", line 368, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 337, in entrypoint\n",
      "    return self._trainable_func(\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 654, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<timed exec>\", line 28, in objective\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 105, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\worker.py\", line 2369, in get\n",
      "    raise ValueError(\n",
      "ValueError: 'object_refs' must either be an ObjectRef or a list of ObjectRefs.\n",
      "2023-04-15 15:28:48,029\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=18840, ip=127.0.0.1, repr=objective)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 803, in ray._raylet.execute_task.function_executor\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 674, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\trainable.py\", line 368, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 337, in entrypoint\n",
      "    return self._trainable_func(\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 654, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<timed exec>\", line 28, in objective\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 105, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\worker.py\", line 2369, in get\n",
      "    raise ValueError(\n",
      "ValueError: 'object_refs' must either be an ObjectRef or a list of ObjectRefs.\n",
      "2023-04-15 15:28:48,329\tERROR trial_runner.py:1062 -- Trial objective_1548b759: Error processing event.\n",
      "ray.exceptions.RayTaskError(ValueError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=18840, ip=127.0.0.1, repr=objective)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 803, in ray._raylet.execute_task.function_executor\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 674, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\trainable.py\", line 368, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 337, in entrypoint\n",
      "    return self._trainable_func(\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 654, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<timed exec>\", line 28, in objective\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 105, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\worker.py\", line 2369, in get\n",
      "    raise ValueError(\n",
      "ValueError: 'object_refs' must either be an ObjectRef or a list of ObjectRefs.\n",
      "2023-04-15 15:28:51,225\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=25588, ip=127.0.0.1, repr=objective)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 803, in ray._raylet.execute_task.function_executor\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 674, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\trainable.py\", line 368, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 337, in entrypoint\n",
      "    return self._trainable_func(\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 654, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<timed exec>\", line 28, in objective\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 105, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\worker.py\", line 2369, in get\n",
      "    raise ValueError(\n",
      "ValueError: 'object_refs' must either be an ObjectRef or a list of ObjectRefs.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-04-15 15:28:52,670\tERROR trial_runner.py:1062 -- Trial objective_9a68262f: Error processing event.\n",
      "ray.exceptions.RayTaskError(ValueError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=8604, ip=127.0.0.1, repr=objective)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 803, in ray._raylet.execute_task.function_executor\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 674, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\trainable.py\", line 368, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 337, in entrypoint\n",
      "    return self._trainable_func(\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 654, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<timed exec>\", line 28, in objective\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 105, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\worker.py\", line 2369, in get\n",
      "    raise ValueError(\n",
      "ValueError: 'object_refs' must either be an ObjectRef or a list of ObjectRefs.\n",
      "2023-04-15 15:28:56,669\tERROR trial_runner.py:1062 -- Trial objective_a966dd12: Error processing event.\n",
      "ray.exceptions.RayTaskError(ValueError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=25588, ip=127.0.0.1, repr=objective)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 803, in ray._raylet.execute_task.function_executor\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 674, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\trainable.py\", line 368, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 337, in entrypoint\n",
      "    return self._trainable_func(\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 654, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<timed exec>\", line 28, in objective\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 105, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\worker.py\", line 2369, in get\n",
      "    raise ValueError(\n",
      "ValueError: 'object_refs' must either be an ObjectRef or a list of ObjectRefs.\n",
      "2023-04-15 15:29:04,151\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=27200, ip=127.0.0.1, repr=objective)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 803, in ray._raylet.execute_task.function_executor\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 674, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\trainable.py\", line 368, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 337, in entrypoint\n",
      "    return self._trainable_func(\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 654, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<timed exec>\", line 28, in objective\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 105, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\worker.py\", line 2369, in get\n",
      "    raise ValueError(\n",
      "ValueError: 'object_refs' must either be an ObjectRef or a list of ObjectRefs.\n",
      "2023-04-15 15:29:07,193\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=12576, ip=127.0.0.1, repr=objective)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 803, in ray._raylet.execute_task.function_executor\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 674, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\trainable.py\", line 368, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 337, in entrypoint\n",
      "    return self._trainable_func(\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 654, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<timed exec>\", line 28, in objective\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 105, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\worker.py\", line 2369, in get\n",
      "    raise ValueError(\n",
      "ValueError: 'object_refs' must either be an ObjectRef or a list of ObjectRefs.\n",
      "2023-04-15 15:29:11,598\tERROR trial_runner.py:1062 -- Trial objective_ce4aab15: Error processing event.\n",
      "ray.exceptions.RayTaskError(ValueError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=12576, ip=127.0.0.1, repr=objective)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 803, in ray._raylet.execute_task.function_executor\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 674, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\trainable.py\", line 368, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 337, in entrypoint\n",
      "    return self._trainable_func(\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 654, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<timed exec>\", line 28, in objective\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 105, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\worker.py\", line 2369, in get\n",
      "    raise ValueError(\n",
      "ValueError: 'object_refs' must either be an ObjectRef or a list of ObjectRefs.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-04-15 15:29:14,287\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=9952, ip=127.0.0.1, repr=objective)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 803, in ray._raylet.execute_task.function_executor\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 674, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\trainable.py\", line 368, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 337, in entrypoint\n",
      "    return self._trainable_func(\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 654, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<timed exec>\", line 28, in objective\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 105, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\worker.py\", line 2369, in get\n",
      "    raise ValueError(\n",
      "ValueError: 'object_refs' must either be an ObjectRef or a list of ObjectRefs.\n",
      "2023-04-15 15:29:14,494\tERROR trial_runner.py:1062 -- Trial objective_957dbe26: Error processing event.\n",
      "ray.exceptions.RayTaskError(ValueError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=27200, ip=127.0.0.1, repr=objective)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 803, in ray._raylet.execute_task.function_executor\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 674, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\trainable.py\", line 368, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 337, in entrypoint\n",
      "    return self._trainable_func(\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 654, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<timed exec>\", line 28, in objective\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 105, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\worker.py\", line 2369, in get\n",
      "    raise ValueError(\n",
      "ValueError: 'object_refs' must either be an ObjectRef or a list of ObjectRefs.\n",
      "2023-04-15 15:29:15,621\tWARNING trial_runner.py:964 -- Trial Runner checkpointing failed: [WinError 5] Zugriff verweigert: 'C:\\\\Users\\\\manue\\\\switchdrive\\\\Mutual Funds Project\\\\ml_prediction\\\\ray_results\\\\xgboost_tuning\\\\.tmp_searcher_ckpt' -> 'C:\\\\Users\\\\manue\\\\switchdrive\\\\Mutual Funds Project\\\\ml_prediction\\\\ray_results\\\\xgboost_tuning\\\\searcher-state-2023-04-15_15-28-17.pkl'\n",
      "2023-04-15 15:29:16,669\tWARNING trial_runner.py:964 -- Trial Runner checkpointing failed: [WinError 5] Zugriff verweigert: 'C:\\\\Users\\\\manue\\\\switchdrive\\\\Mutual Funds Project\\\\ml_prediction\\\\ray_results\\\\xgboost_tuning\\\\.tmp_searcher_ckpt' -> 'C:\\\\Users\\\\manue\\\\switchdrive\\\\Mutual Funds Project\\\\ml_prediction\\\\ray_results\\\\xgboost_tuning\\\\searcher-state-2023-04-15_15-28-17.pkl'\n",
      "2023-04-15 15:29:23,399\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=26844, ip=127.0.0.1, repr=objective)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 803, in ray._raylet.execute_task.function_executor\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 674, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\trainable.py\", line 368, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 337, in entrypoint\n",
      "    return self._trainable_func(\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 654, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<timed exec>\", line 28, in objective\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 105, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\worker.py\", line 2369, in get\n",
      "    raise ValueError(\n",
      "ValueError: 'object_refs' must either be an ObjectRef or a list of ObjectRefs.\n",
      "2023-04-15 15:29:25,534\tERROR trial_runner.py:1062 -- Trial objective_a9008590: Error processing event.\n",
      "ray.exceptions.RayTaskError(ValueError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=26844, ip=127.0.0.1, repr=objective)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 803, in ray._raylet.execute_task.function_executor\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 674, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\trainable.py\", line 368, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 337, in entrypoint\n",
      "    return self._trainable_func(\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 654, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<timed exec>\", line 28, in objective\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 105, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\worker.py\", line 2369, in get\n",
      "    raise ValueError(\n",
      "ValueError: 'object_refs' must either be an ObjectRef or a list of ObjectRefs.\n",
      "2023-04-15 15:29:26,718\tERROR trial_runner.py:1062 -- Trial objective_db4170ce: Error processing event.\n",
      "ray.exceptions.RayTaskError(ValueError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=9952, ip=127.0.0.1, repr=objective)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 803, in ray._raylet.execute_task.function_executor\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 674, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\trainable.py\", line 368, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 337, in entrypoint\n",
      "    return self._trainable_func(\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 654, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<timed exec>\", line 28, in objective\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 105, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\worker.py\", line 2369, in get\n",
      "    raise ValueError(\n",
      "ValueError: 'object_refs' must either be an ObjectRef or a list of ObjectRefs.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-04-15 15:29:26,724\tERROR trial_runner.py:1062 -- Trial objective_2c5bede9: Error processing event.\n",
      "ray.exceptions.RayTaskError(ValueError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=16108, ip=127.0.0.1, repr=objective)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 803, in ray._raylet.execute_task.function_executor\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 674, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\trainable.py\", line 368, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 337, in entrypoint\n",
      "    return self._trainable_func(\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 654, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<timed exec>\", line 28, in objective\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 105, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\worker.py\", line 2369, in get\n",
      "    raise ValueError(\n",
      "ValueError: 'object_refs' must either be an ObjectRef or a list of ObjectRefs.\n",
      "2023-04-15 15:29:33,637\tERROR trial_runner.py:1062 -- Trial objective_e5d33a9b: Error processing event.\n",
      "ray.exceptions.RayTaskError(ValueError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=5388, ip=127.0.0.1, repr=objective)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 803, in ray._raylet.execute_task.function_executor\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 674, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\trainable.py\", line 368, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 337, in entrypoint\n",
      "    return self._trainable_func(\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 654, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<timed exec>\", line 28, in objective\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 105, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\manue\\anaconda3\\lib\\site-packages\\ray\\_private\\worker.py\", line 2369, in get\n",
      "    raise ValueError(\n",
      "ValueError: 'object_refs' must either be an ObjectRef or a list of ObjectRefs.\n"
     ]
    },
    {
     "ename": "TuneError",
     "evalue": "('Trials did not complete', [objective_bb5b8fc1, objective_9a68262f, objective_1548b759, objective_a966dd12, objective_957dbe26, objective_ce4aab15, objective_db4170ce, objective_a9008590, objective_2c5bede9, objective_e5d33a9b])",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mTuneError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[1;32m<timed exec>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n",
      "\u001b[1;32m~\\anaconda3\\lib\\site-packages\\ray\\tune\\tune.py\u001b[0m in \u001b[0;36mrun\u001b[1;34m(run_or_experiment, name, metric, mode, stop, time_budget_s, config, resources_per_trial, num_samples, local_dir, search_alg, scheduler, keep_checkpoints_num, checkpoint_score_attr, checkpoint_freq, checkpoint_at_end, verbose, progress_reporter, log_to_file, trial_name_creator, trial_dirname_creator, chdir_to_trial_dir, sync_config, export_formats, max_failures, fail_fast, restore, server_port, resume, reuse_actors, raise_on_failed_trial, callbacks, max_concurrent_trials, trial_executor, _experiment_checkpoint_dir, _remote, _remote_string_queue)\u001b[0m\n\u001b[0;32m    790\u001b[0m     \u001b[1;32mif\u001b[0m \u001b[0mincomplete_trials\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    791\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0mraise_on_failed_trial\u001b[0m \u001b[1;32mand\u001b[0m \u001b[1;32mnot\u001b[0m \u001b[0mexperiment_interrupted_event\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mis_set\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 792\u001b[1;33m             \u001b[1;32mraise\u001b[0m \u001b[0mTuneError\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"Trials did not complete\"\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mincomplete_trials\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    793\u001b[0m         \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    794\u001b[0m             \u001b[0mlogger\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0merror\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"Trials did not complete: %s\"\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mincomplete_trials\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mTuneError\u001b[0m: ('Trials did not complete', [objective_bb5b8fc1, objective_9a68262f, objective_1548b759, objective_a966dd12, objective_957dbe26, objective_ce4aab15, objective_db4170ce, objective_a9008590, objective_2c5bede9, objective_e5d33a9b])"
     ]
    }
   ],
   "source": [
    "%%time\n",
    "import xgboost as xgb\n",
    "from hyperopt import hp, fmin, tpe, Trials\n",
    "from ray import tune\n",
    "from ray.tune.schedulers import AsyncHyperBandScheduler\n",
    "from ray.tune.search.hyperopt import HyperOptSearch\n",
    "from sklearn.model_selection import cross_val_score, KFold\n",
    "import numpy as np\n",
    "\n",
    "\n",
    "# Define the search space for hyperparameters\n",
    "search_space = {\n",
    "    \"learning_rate\": hp.loguniform(\"learning_rate\", np.log(0.0001), np.log(0.9)),\n",
    "    \"max_depth\": hp.choice(\"max_depth\", range(1, 16)),\n",
    "    \"n_estimators\": hp.choice(\"n_estimators\", range(100, 10000)),\n",
    "    \"subsample\": hp.uniform(\"subsample\", 0.5, 1),\n",
    "    \"colsample_bytree\": hp.uniform(\"colsample_bytree\", 0.5, 1),\n",
    "    \"colsample_bylevel\": hp.uniform(\"colsample_bylevel\", 0.5, 1),\n",
    "    \"reg_alpha\": hp.loguniform(\"reg_alpha\", np.log(0.001), np.log(100)),\n",
    "    \"reg_lambda\": hp.loguniform(\"reg_lambda\", np.log(0.001), np.log(100)),\n",
    "}\n",
    "\n",
    "\n",
    "kfolds = KFold(n_splits=5, shuffle=True, random_state=26)\n",
    "\n",
    "# Define the objective function to optimize\n",
    "def objective(config):\n",
    "    model = xgb.XGBRegressor(**config, n_jobs=-1)\n",
    "    score = cross_val_score(model, X=ray.get(X_train), y=ray.get(y_train), scoring=\"neg_mean_squared_error\", cv=kfolds)\n",
    "    rmse = np.sqrt(-np.mean(score))\n",
    "    tune.report(rmse=rmse)\n",
    "\n",
    "# Define the search algorithm\n",
    "search_alg = HyperOptSearch(space=search_space, metric=\"rmse\", mode=\"min\")\n",
    "# to limit number of cores, uncomment and set max_concurrent \n",
    "# algo = ConcurrencyLimiter(algo, max_concurrent=10)\n",
    "scheduler = AsyncHyperBandScheduler()\n",
    "\n",
    "# Define the hyperparameter tuning trials object\n",
    "trials = Trials()\n",
    "\n",
    "# Define the configuration for Ray Tune\n",
    "config = {\n",
    "    'num_samples': 10,\n",
    "    'config': search_space,\n",
    "    'search_alg': search_alg,\n",
    "    'scheduler': scheduler,\n",
    "    'resources_per_trial': {'cpu': 1},\n",
    "    'metric': 'rmse',\n",
    "    'mode': 'min',\n",
    "    'verbose': 1,\n",
    "    'name': 'xgboost_tuning',\n",
    "    'stop': {'training_iteration': 10},\n",
    "    'local_dir': './ray_results',\n",
    "}\n",
    "\n",
    "# Start the hyperparameter tuning using Ray Tune\n",
    "analysis = tune.run(objective, **config)\n",
    "\n",
    "# Print the best hyperparameters found during the search\n",
    "best_params = analysis.get_best_config(metric='rmse')\n",
    "print(\"Best hyperparameters found:\")\n",
    "print(best_params)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "7b7fcce4",
   "metadata": {},
   "source": [
    "### Distributed Ray XGB\n",
    "https://github.com/ray-project/xgboost_ray"
   ]
  },
  {
   "cell_type": "raw",
   "id": "e305164c",
   "metadata": {},
   "source": [
    "import time\n",
    "from ray.tune.schedulers import ASHAScheduler\n",
    "from ray.tune.search.hyperopt import HyperOptSearch\n",
    "from xgboost_ray import RayDMatrix, RayParams, train\n",
    "from ray import tune\n",
    "\n",
    "def train_xgboost(config, checkpoint_dir=None):\n",
    "    start_time = time.time()\n",
    "    \n",
    "    train_set = RayDMatrix(X_train, y_train)\n",
    "    test_set = RayDMatrix(X_test, y_test)\n",
    "    \n",
    "    evals_result = {}\n",
    "    \n",
    "    # train the model\n",
    "    bst = train(\n",
    "        params=config,\n",
    "        dtrain=train_set,\n",
    "        evals_result=evals_result,\n",
    "        evals=[(test_set, \"eval\")],\n",
    "        verbose_eval=False,\n",
    "        num_boost_round=5, #equivalent to 'epochs'\n",
    "        ray_params=RayParams(num_actors=4, cpus_per_actor=2)) #parameters for parallelism\n",
    "    \n",
    "    model_path = 'model.xgb'\n",
    "    bst.save_model(model_path)\n",
    "    print(f'total time taken: {time.time()-start_time}')\n",
    "    print('Final rmse: {:.4f}'.format(\n",
    "    evals_result[\"eval\"][\"rmse\"][-1]))\n",
    "    \n",
    "    return bst\n",
    "    \n",
    "\n",
    "# Define the search algorithm and scheduler\n",
    "#### NOT SURE IF NEEDED OR SUPPORTED IN XGB_RAY! maybe uncomment here and in config\n",
    "search_alg = HyperOptSearch()\n",
    "scheduler = ASHAScheduler(max_t=10, grace_period=1)\n",
    "\n",
    "# Specify the hyperparameter search space.\n",
    "config = {\n",
    "    \"tree_method\": \"approx\",\n",
    "    \"objective\": \"reg:squarederror\", # Use regression objective\n",
    "    \"eval_metric\": \"rmse\", # Set the evaluation metric to RMSE\n",
    "    \"learning_rate\": tune.loguniform(1e-4, 0.9),\n",
    "    \"subsample\": tune.uniform(0.8, 1.0),\n",
    "    \"colsample_bytree\": tune.uniform(0.8, 1.0),\n",
    "    \"colsample_bylevel\": tune.uniform(0.8, 1.0),\n",
    "    \"max_depth\": tune.randint(1, 16),\n",
    "    \"n_estimators\": tune.randint(500, 10000),\n",
    "    \"reg_alpha\": tune.loguniform(1e-3, 100),\n",
    "    \"reg_lambda\": tune.loguniform(1e-3, 100),\n",
    "}\n",
    "\n",
    "# Run the hyperparameter search\n",
    "analysis = tune.run(\n",
    "    train_xgboost,\n",
    "    resources_per_trial=RayParams(num_actors=4, cpus_per_actor=2).get_tune_resources(),\n",
    "    config=config,\n",
    "    num_samples=5,\n",
    "    search_alg=search_alg,\n",
    "    scheduler=scheduler,\n",
    "    metric='rmse',\n",
    "    mode='min',\n",
    "    verbose=1\n",
    ")\n",
    "\n",
    "best_RMSE = analysis.best_result[\"rmse\"]\n",
    "print(f'Best model parameters: {analysis.best_config}')\n",
    "print(f'Best RMSE: {best_RMSE}')\n",
    "print(analysis.best_config)\n"
   ]
  },
  {
   "cell_type": "raw",
   "id": "fb1d6096",
   "metadata": {},
   "source": [
    "sample.to_pickle('sample.pkl')"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
